In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
ds = pd.read_csv('Position_Salaries.csv')
X = ds.iloc[:,1 : -1].values
y = ds.iloc[:, -1].values

In [19]:
print(X)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [20]:
y = y.reshape(len(y),1)

In [21]:
print(y)

[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [22]:
from sklearn.ensemble import RandomForestRegressor

In [23]:
regressor = RandomForestRegressor(n_estimators = 10,random_state = 0)

In [24]:
regressor.fit(X,y)

C:\Users\Home\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [25]:
regressor.predict([[6.5]])

array([167000.])

In [26]:
X_grid = np.arange(min(X),max(X),0.1)
X_grid = X_grid.reshape(len(X_grid),1)

In [2]:
plt.scatter(X,y,color = 'red')
plt.plot(X_grid,regressor.predict(X_grid),color = 'blue')
plt.title(' RANDOM FOREST REGRESSION')
plt.xlabel('position_level')
plt.ylabel('salary')
plt.show()

NameError: name 'plt' is not defined